sudo docker image rm fun/open5gs-nrf:v2.7.0
sudo docker image rm fun/open5gs-scp:v2.7.0
sudo docker image rm fun/open5gs-sepp:v2.7.0
sudo docker image rm fun/open5gs-amf:v2.7.0
sudo docker image rm fun/open5gs-smf:v2.7.0
sudo docker image rm fun/open5gs-upf:v2.7.0
sudo docker image rm fun/open5gs-ausf:v2.7.0
sudo docker image rm fun/open5gs-udm:v2.7.0
sudo docker image rm fun/open5gs-udr:v2.7.0
sudo docker image rm fun/open5gs-pcf:v2.7.0
sudo docker image rm fun/open5gs-nssf:v2.7.0
sudo docker image rm fun/open5gs-bsf:v2.7.0
sudo docker image rm fun/open5gs-webui:v2.7.0
sudo docker image rm fun/open5gs-base:v2.7.0
